import type { Form } from './types';

export const EMPTY: Form = {
  type: 'multiple_choice',
  seedKey: '',
  category: 'orthography',
  difficulty: 1,
  qualityStatus: 'draft',
  prompt: '',
  explanation: '',
  skillTags: 'ege.14',
  sourceAlignment: '',
  typicalMistake: '',
  algorithmSteps: '',
  isActive: true,
  options: ['', ''],
  correctOptionIndex: 0,
  multiCorrectOptionIndexes: '',
  fillBefore: '',
  fillAfter: '',
  fillAccepted: '',
  fillCaseSensitive: false,
  wordBankTextWithSlots: '',
  wordBankWords: '',
  wordBankCorrectBySlot: '',
  wordBankCaseSensitive: false,
  wordSearchGridRows: '',
  wordSearchWords: '',
  wordSearchCaseSensitive: false,
  dictationTitle: '',
  dictationAudioSrc: '',
  dictationPlaybackRates: '0.75, 1, 1.25, 1.5',
  dictationText: '',
  dictationCaseSensitive: false,
  dictationIgnorePunctuation: false,
  orthographyRepairText: '',
  orthographyRepairMode: 'click_then_choose',
  orthographyRepairTargets: '',
  orthographyRepairHints: '',
  orthographyRepairRepairs: '',
  orthographyRepairCorrectText: '',
  orderFragments: '',
  orderCorrectOrder: '',
  punctuationTokens: '',
  punctuationAllowedMarks: ',',
  punctuationMarks: '',
  punctuationConstructorTokens: '',
  punctuationConstructorMarkBank:
    'period, comma, semicolon, colon, question, exclamation, quote_open, quote_close, paren_open, paren_close, dash, ellipsis',
  punctuationConstructorHints: '',
  punctuationConstructorGuidedSteps: '',
  punctuationConstructorSegments: '',
  punctuationConstructorPlacements: '',
  punctuationConstructorSlotExplanations: '',
  ege20TextWithSlots: '',
  ege20Slots: '',
  ege20TargetSet: '',
  ege21TargetPunctuation: 'comma',
  ege21Sentences: '',
  ege21TargetSet: '',
};
